import { Link } from "react-router-dom";

const privacySections = [
  {
    title: "1. Data We Collect",
    content:
      "We collect certain personally identifiable information (PII) when users sign in via Google through Clerk. This includes:",
    list: [
      "Full name associated with the Google account.",
      "Primary email address of the user.",
      "A unique user ID generated by Clerk.",
      "Patreon member ID and pledge tier (if the user links their Patreon account).",
      "Timestamp of account creation.",
      "URLs submitted for summarization (if the user opts to save them).",
      "The corresponding TL;DR summaries (if the user opts to save them).",
    ],
    extra: (
      <>
        This information is used solely to provide authentication,
        personalization, and save history functionality. Patreon account data is
        used to verify eligibility for increased rate limits. We do not collect
        or store passwords or payment details. Authentication is handled
        securely via{" "}
        <a href="https://clerk.com" target="_blank" rel="noopener noreferrer">
          Clerk
        </a>
        . Patreon data is accessed securely via their official API.
      </>
    ),
  },
  {
    title: "2. Third-Party Services",
    content:
      "We use third-party services for authentication and AI-based summarization:",
    list: [
      <a
        href="https://clerk.com/legal/privacy"
        target="_blank"
        rel="noopener noreferrer"
      >
        Clerk Privacy Policy
      </a>,
      <a
        href="https://openai.com/policies/privacy-policy"
        target="_blank"
        rel="noopener noreferrer"
      >
        OpenAI Privacy Policy
      </a>,
      <a
        href="https://www.patreon.com/policy"
        target="_blank"
        rel="noopener noreferrer"
      >
        Patreon Privacy Policy
      </a>,
    ],
    extra:
      "These services may collect and process data independently, in accordance with their own privacy policies. " +
      "We use Clerk for authentication, OpenAI for AI-powered summaries, and Patreon to verify supporter status for enhanced rate limits. We do not control or take responsibility for how these providers handle data once shared.",
  },
  {
    title: "3. Use of Cookies",
    content:
      "We use cookies/browser storage to manage user sessions securely via Clerk. These are necessary for authentication, and session management.",
  },
  {
    title: "4. Data Security",
    content:
      "We implement industry-standard security measures to protect stored TL;DRs and URLs. However, we cannot guarantee absolute security due to the nature of the internet.",
  },
  {
    title: "5. Your Rights",
    content: "You have the right to:",
    list: [
      "Request deletion of your account and all associated data.",
      "Request deletion of any saved TL;DRs and URLs individually.",
      "Opt not to save any summaries by disabling the save feature.",
    ],
  },
  {
    title: "6. Changes to This Policy",
    content:
      "We may update this Privacy Policy from time to time. Changes will be reflected on this page with a revised 'Last Updated' date.",
  },
  {
    title: "7. Contact Us",
    content:
      "If you have any questions about this Privacy Policy, please contact us at,",
    list: [
      <a
        href="mailto:contact@prathamjaiswal.com"
        target="_blank"
        rel="noopener noreferrer"
      >
        contact@prathamjaiswal.com
      </a>,
      <a
        href="mailto:prathamj0502@gmail.com"
        target="_blank"
        rel="noopener noreferrer"
      >
        prathamj0502@gmail.com
      </a>,
    ],
  },
];

export default function PrivacyPolicy() {
  return (
    <div className="policy-container">
      <div className="header">
        <div className="header-left-icon">
          <Link to="/">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              height="24px"
              viewBox="0 -960 960 960"
              width="24px"
              fill="#F4EEE0"
            >
              <path d="M240-200h120v-240h240v240h120v-360L480-740 240-560v360Zm-80 80v-480l320-240 320 240v480H520v-240h-80v240H160Zm320-350Z" />
            </svg>
          </Link>
        </div>
        <div className="policy-header">
          <h1>Privacy Policy</h1>
          <p>Last Updated: <i>04th May 2025</i></p>
        </div>
      </div>

      <div className="policy-content">
        {privacySections.map(({ title, content, list, extra }, index) => (
          <div key={index} className="policy-box">
            <h2>{title}</h2>
            <p>{content}</p>
            {list && (
              <ul>
                {list.map((item, i) => (
                  <li key={i}>{item}</li>
                ))}
              </ul>
            )}
            {extra && <p>{extra}</p>}
          </div>
        ))}
      </div>
    </div>
  );
}
